name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */24 * * *"  # Menjalankan setiap 24 jam
  workflow_dispatch:  # Menjalankan manual
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    timeout-minutes: 5

    steps:
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: radityatamanugraha # Ganti dengan username GitHub kamu
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push Snake Image to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          source_dir: 'dist'
          target_branch: gh-pages
